assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock

ga_analytics: # Add Google Analytics tracking code

plugins:
  # - jekyll-pandoc-multiple-formats
  - jekyll-assets
  - jekyll-sitemap

name: foo


pandoc:
    skip: false
    full_file: true
    bundle_permalink: ':slug.:output_ext'
    papersize: 'a5paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    # covers_dir: assets/covers
    signature: 20

    flags: '-f markdown+smart+pipe_tables+footnotes'
    site_flags: '--toc'
    outputs:
      epub: '--epub-chapter-level=2'

permalink: pretty

url: "https://foo.com"

title: Register design patters
description: Primer is a Jekyll theme for GitHub Pages

markdown: pandoc
