baseurl: '/register-design-patterns'

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  compression: true
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
    gzip: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/*

ga_analytics: # Add Google Analytics tracking code

plugins:
  - jekyll-assets
  - jekyll-sitemap

pandoc:
    skip: true
    full_file: true
    bundle_permalink: ':slug.:output_ext'
    papersize: 'a5paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    # covers_dir: assets/covers
    signature: 20

    flags: '-f markdown+smart+pipe_tables+footnotes+autolink_bare_uris'
    site_flags: '--toc'
    outputs:
      epub: '--epub-chapter-level=1'

permalink: pretty

# url: "https://foo.com"

title: Registers and custodianship
description: Primer is a Jekyll theme for GitHub Pages

markdown: pandoc

collections:
  terms:
    output: true
    permalink: /:collection/:name


defaults:
  - scope:
      path: ""
      type: terms
    values:
      item_name: "Term"
