baseurl: '/register-design-patterns'

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock
  - vendor/*

ga_analytics: # Add Google Analytics tracking code

plugins:
  # - jekyll-pandoc-multiple-formats
  - jekyll-assets
  - jekyll-sitemap

pandoc:
    skip: true
    full_file: true
    bundle_permalink: ':slug.:output_ext'
    papersize: 'a5paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    # covers_dir: assets/covers
    signature: 20

    flags: '-f markdown+smart+pipe_tables+footnotes+autolink_bare_uris'
    site_flags: '--toc'
    outputs:
      epub: '--epub-chapter-level=2'

permalink: pretty

# url: "https://foo.com"

title: Register design patterns
description: Primer is a Jekyll theme for GitHub Pages

markdown: pandoc

collections:
  list_properties:
    output: true
    permalink: /:collection/:name
  governance_patterns:
    output: true
    permalink: /:collection/:name


defaults:
  - scope:
      path: ""
      type: list_properties
    values:
      item_name: "List property"
  - scope:
      path: ""
      type: governance_patterns
    values:
      item_name: "Governance pattern"
